Repository PrestaShopCorp/ps_mbo, pull requests merged in 2022-11, with the labels that each got.

#327 Add domains to translatable strings
  src/Traits/Hooks/UseDisplayDashboardTop.php
Labels: 4.1.x

#323 [MBO-466] feat :chart_with_upwards_trend: Start to track module actions
  config/services/addons.php
  config/services/cdc.yml
  src/Accounts/Provider/AccountsDataProvider.php
  src/Addons/Subscriber/ModuleManagementEventSubscriber.php
  src/Distribution/Client.php
  src/Helpers/AsyncClient.php
  src/Service/View/ContextBuilder.php
Labels: prestabulle1, 4.1.x, new feature

#353 Fix :bug: Force the version to be SemVer to avoid having 1.8.0.0 parameter
  config/services/addons.yml
Labels: 4.1.x

#351 Feat :chart_with_upwards_trend: Add version on link presents in searc…
  src/Traits/Hooks/UseActionGetAlternativeSearchPanels.php
Labels: prestabulle1, 4.1.x

#354 Fix :bug: Do not block processes if ps_account is not installed
  src/Accounts/Provider/AccountsDataProvider.php
Labels: 4.1.x

#335 Feat :sparkles: New settings page to handle tests environments
  .github/workflows/build-release.yml
  ps_mbo.php
  src/Traits/HaveConfigurationPage.php
Labels: 4.1.x, new feature
