Repository PrestaShopCorp/ps_mbo, pull requests merged in 2023-02, with the labels that each got.

#418 [MBO-504][MBO-538] Use Accounts token to request Addons API #408
  config/services/addons.yml
  src/Accounts/Provider/AccountsDataProvider.php
  src/Addons/ApiClient.php
  src/Addons/Provider/AddonsDataProvider.php
  src/Addons/Toolbar.php
  src/Addons/User/AddonsUser.php
  src/Addons/User/AddonsUserProvider.php
  src/Api/Service/ModuleTransitionExecutor.php
  src/Distribution/ConnectedClient.php
  src/Service/View/ContextBuilder.php
  src/Traits/Hooks/UseActionAdminControllerSetMedia.php
  translations/de-DE/ModulesMboModulescatalog.de-DE.xlf
  translations/en-US/ModulesMboModulescatalog.en-US.xlf
  translations/es-ES/ModulesMboModulescatalog.es-ES.xlf
  translations/fr-FR/ModulesMboModulescatalog.fr-FR.xlf
  translations/it-IT/ModulesMboModulescatalog.it-IT.xlf
  translations/nl-NL/ModulesMboModulescatalog.nl-NL.xlf
  translations/pl-PL/ModulesMboModulescatalog.pl-PL.xlf
  translations/pt-PT/ModulesMboModulescatalog.pt-PT.xlf
  translations/ru-RU/ModulesMboModulescatalog.ru-RU.xlf
  views/css/connection-toolbar.css
  views/js/connection-toolbar.js
Labels: 4.x, 4.3

#415 [MBO-629] Add mbo version, ps version & shop URL in context.
  .github/workflows/build-release.yml
  src/Service/View/ContextBuilder.php
Labels: 4.x, 4.3

#390 Change Nest URL to get employee menu
  src/Addons/User/AddonsUser.php
  src/Distribution/Client.php
  src/Traits/Hooks/UseDisplayBackOfficeEmployeeMenu.php
  translations/pt-PT/ModulesMboErrors.pt-PT.xlf
Labels: 4.x, 4.3

#397 [MBO-613] Make tabs disabled on upgrade
  ps_mbo.php
  src/Traits/HaveTabs.php
  src/Traits/Hooks/UseActionDispatcherBefore.php
Labels: 4.x, 4.3

#412 [MBO-641] Switch Module Manager and Marketplace menus + Bump version to 4.2.1
  ps_mbo.php
  src/Controller/Admin/ModuleSelectionController.php
  src/Traits/HaveTabs.php
  src/Traits/Hooks/UseActionDispatcherBefore.php
  translations/de-DE/ModulesMboModulesselection.de-DE.xlf
  translations/en-US/ModulesMboModulesselection.en-US.xlf
  translations/es-ES/ModulesMboModulesselection.es-ES.xlf
  translations/fr-FR/ModulesMboModulesselection.fr-FR.xlf
  translations/it-IT/ModulesMboModulesselection.it-IT.xlf
  translations/nl-NL/ModulesMboModulesselection.nl-NL.xlf
  translations/pl-PL/ModulesMboModulesselection.pl-PL.xlf
  translations/pt-PT/ModulesMboModulesselection.pt-PT.xlf
  translations/ru-RU/ModulesMboModulesselection.ru-RU.xlf
  upgrade/upgrade-4.2.1.php
Labels: 4.3

#420 4.3.x
  .github/workflows/build-release.yml
  .github/workflows/php.yml
  bootstrap.php
  composer.json
  config.xml
  config/services/addons.yml
  ps_mbo.php
  src/Accounts/Provider/AccountsDataProvider.php
  src/Addons/ApiClient.php
  src/Addons/Provider/AddonsDataProvider.php
  src/Addons/Toolbar.php
  src/Addons/User/AddonsUser.php
  src/Addons/User/AddonsUserProvider.php
  src/Api/Service/ModuleTransitionExecutor.php
  src/Controller/Admin/ModuleSelectionController.php
  src/Distribution/Client.php
  src/Distribution/ConnectedClient.php
  src/Service/View/ContextBuilder.php
  src/Traits/HaveTabs.php
  src/Traits/Hooks/UseActionAdminControllerSetMedia.php
  src/Traits/Hooks/UseActionDispatcherBefore.php
  src/Traits/Hooks/UseDisplayBackOfficeEmployeeMenu.php
  translations/de-DE/ModulesMboModulescatalog.de-DE.xlf
  translations/de-DE/ModulesMboModulesselection.de-DE.xlf
  translations/en-US/ModulesMboModulescatalog.en-US.xlf
  translations/en-US/ModulesMboModulesselection.en-US.xlf
  translations/es-ES/ModulesMboModulescatalog.es-ES.xlf
  translations/es-ES/ModulesMboModulesselection.es-ES.xlf
  translations/fr-FR/ModulesMboModulescatalog.fr-FR.xlf
  translations/fr-FR/ModulesMboModulesselection.fr-FR.xlf
  translations/it-IT/ModulesMboModulescatalog.it-IT.xlf
  translations/it-IT/ModulesMboModulesselection.it-IT.xlf
  translations/nl-NL/ModulesMboModulescatalog.nl-NL.xlf
  translations/nl-NL/ModulesMboModulesselection.nl-NL.xlf
  translations/pl-PL/ModulesMboModulescatalog.pl-PL.xlf
  translations/pl-PL/ModulesMboModulesselection.pl-PL.xlf
  translations/pt-PT/ModulesMboErrors.pt-PT.xlf
  translations/pt-PT/ModulesMboModulescatalog.pt-PT.xlf
  translations/pt-PT/ModulesMboModulesselection.pt-PT.xlf
  translations/ru-RU/ModulesMboModulescatalog.ru-RU.xlf
  translations/ru-RU/ModulesMboModulesselection.ru-RU.xlf
  upgrade/upgrade-4.2.1.php
  views/css/connection-toolbar.css
  views/js/connection-toolbar.js
Labels: 4.3

#425 [MBO-664][MBO-665][MBO-660] Improve module catalog
  config/routes.yml
  config/services.yml
  ps_mbo.php
  src/Controller/Admin/ModuleCatalogController.php
  src/Controller/Admin/ModuleController.php
  views/css/catalog.css
  views/templates/admin/controllers/module_catalog/Includes/catalog_card.html.twig
  views/templates/admin/controllers/module_catalog/Includes/menu_top.html.twig
  views/templates/admin/controllers/module_catalog/Includes/module_actions_buttons.html.twig
  views/templates/admin/controllers/module_catalog/Includes/sorting.html.twig
  views/templates/admin/controllers/module_catalog/catalog.html.twig
  views/templates/admin/controllers/module_catalog/catalog_grid.html.twig
Labels: 2.x

#422 [MBO-662][MBO-663][MBO-668][MBO-670]feat: :sparkles: design button and customization title and description recommended modules modal
  ps_mbo.php
  views/css/recommended-modules-lower-1.7.8.css
  views/css/recommended-modules-since-1.7.8.css
  views/css/recommended-modules.css
  views/js/recommended-modules.js
  views/templates/admin/controllers/module_catalog/recommended-modules.html.twig
  views/templates/hook/recommended-modules.tpl
Labels: 2.x
